# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65b578540ebeb185533f44d5df6867fa5518e7354e1af102ea5b5914d325924709a27c09a55f823090afe70a9266246b3d4026fea1202bc7e5c5a19417725ef5

test:
  secret_key_base: 2a659a013b92e05e4a5eb3fdc27c38350343a2263eb885a4cd3e2bbc8fa97ebf23c0a7586aceea0cdd7c0bc2a8a0143e6c5dd7a2096b2e146b4a9f39d2a91fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
